cluster_name: dbl25tst01w08
tls:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIICDzCCAbWgAwIBAgIRAMtND8pipxgoC+YPvgFlhiAwCgYIKoZIzj0EAwIwLjEV
    MBMGA1UEChMMVHJhZWZpayBMYWJzMRUwEwYDVQQDEwxUcmFlZmlrRUUgQ0EwIBcN
    MjUwMjE3MTMwODIzWhgPMjEyNTAxMjQxMzA4MjNaMB8xHTAbBgNVBAMTFGNsaWVu
    dC5kYmwyNXRzdDAxdzA4MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEV1dET8ju
    oAjXfLm5BKRS4nPtTib4+3ZdywDjiTPYYTHZxX+oUD8w6i97bRULyxCV7Ykwt/Jh
    bKPUTI6+sO8Y0KOBwDCBvTAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYB
    BQUHAwIwDAYDVR0TAQH/BAIwADApBgNVHQ4EIgQgM2zpRkkC94P8fbijpCKckfqa
    ejS2E9IDRJZP0FnFeoowKwYDVR0jBCQwIoAgYsPjzy3qAmG2b64jbnA59t542iBm
    7XnwnKhTh+3g27MwMAYDVR0RBCkwJ4IUY2xpZW50LmRibDI1dHN0MDF3MDiCCWxv
    Y2FsaG9zdIcEfwAAATAKBggqhkjOPQQDAgNIADBFAiAc9CwiPmcxVLCsWHQE2Xpp
    henV5VNvCWRSAsCKIjZ3iQIhAPEbvh7zz9wMowQw5QKPK0vLET3tCbHbYRJ2/A5X
    K+Ew
    -----END CERTIFICATE-----
  key: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIMu8wvJgCjnIkdsIqivCLGxMZOObP5Y4zg/+UanRzdaSoAoGCCqGSM49
    AwEHoUQDQgAEV1dET8juoAjXfLm5BKRS4nPtTib4+3ZdywDjiTPYYTHZxX+oUD8w
    6i97bRULyxCV7Ykwt/JhbKPUTI6+sO8Y0A==
    -----END EC PRIVATE KEY-----
  ca: |
    -----BEGIN CERTIFICATE-----
    MIIB2DCCAX2gAwIBAgIQCbI288y9fjxmb0qdvX1p9DAKBggqhkjOPQQDAjAuMRUw
    EwYDVQQKEwxUcmFlZmlrIExhYnMxFTATBgNVBAMTDFRyYWVmaWtFRSBDQTAgFw0y
    NTAyMTcxMzA2MTJaGA8yMTI1MDEyNDEzMDYxMlowLjEVMBMGA1UEChMMVHJhZWZp
    ayBMYWJzMRUwEwYDVQQDEwxUcmFlZmlrRUUgQ0EwWTATBgcqhkjOPQIBBggqhkjO
    PQMBBwNCAASpKjZtohJkxFSgw75fYGV6L0WSAkPRUx0TYfPmKTm1O4qou5rm1A8a
    8me5WH47efNi6gmaS2GPi5tSPuhTH+SEo3sweTAOBgNVHQ8BAf8EBAMCAYYwDwYD
    VR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgYsPjzy3qAmG2b64jbnA59t542iBm7Xnw
    nKhTh+3g27MwKwYDVR0jBCQwIoAgYsPjzy3qAmG2b64jbnA59t542iBm7XnwnKhT
    h+3g27MwCgYIKoZIzj0EAwIDSQAwRgIhAM/d7AAc5MoQdIf+kV4hgHAbr10ee9UJ
    oX9I3BQ72la7AiEAksHx8QkdNeD4wyshNqMa9kDhgoj+cC88PFCNWDUEwwQ=
    -----END CERTIFICATE-----
kubernetes:
  config_path: /Users/newa/Documents/traefik/git/eeacme-to-acmejson/kubeconfig
  namespace: traefikee
  forwarded_port: 0
pluginregistrytoken: ""
